/*************************************************************************************************
 * Copyright 2022-2025 Theai, Inc. dba Inworld AI
 *
 * Use of this source code is governed by the Inworld.ai Software Development Kit License Agreement
 * that can be found in the LICENSE.md file or at https://www.inworld.ai/sdk-license
 *************************************************************************************************/

using System;

namespace Inworld.Framework
{
    /// <summary>
    /// Represents speech content generated by an agent within the Inworld framework.
    /// Contains the spoken utterance and associated agent information for voice interactions.
    /// Used for handling and processing agent-generated speech in conversation workflows.
    /// </summary>
    public class InworldAgentSpeech : InworldFrameworkDllClass
    {
        /// <summary>
        /// Initializes a new instance of the InworldAgentSpeech class from a native pointer.
        /// </summary>
        /// <param name="rhs">The native pointer to the agent speech object.</param>
        public InworldAgentSpeech(IntPtr rhs)
        {
            m_DLLPtr = MemoryManager.Register(rhs, InworldInterop.inworld_AgentSpeech_delete);
        }
        
        /// <summary>
        /// Gets or sets the name of the agent that generated this speech.
        /// Identifies which agent is speaking in multi-agent scenarios.
        /// </summary>
        public string AgentName
        {
            get => InworldInterop.inworld_AgentSpeech_agent_name_get(m_DLLPtr);
            set => InworldInterop.inworld_AgentSpeech_agent_name_set(m_DLLPtr, value);
        }

        /// <summary>
        /// Gets or sets the actual speech utterance content.
        /// Contains the text that the agent is speaking or has spoken.
        /// </summary>
        public string Utterance
        {
            get => InworldInterop.inworld_AgentSpeech_utterance_get(m_DLLPtr);
            set => InworldInterop.inworld_AgentSpeech_utterance_set(m_DLLPtr, value);
        }
    }
}